### ISSUE TITLE
Attribute group capital letters validation failing

### ISSUE THREAD

**Issue by kardi31** [ergonode/backend#1161]
## Bug type
Code

## Current behavior
When trying to submit attribute group with a capital letter, the validation fails. Error message says "System name can have only letters, digits or underscore symbol"

## Expected behavior
If capital letters are not allowed in attribute groups, the message should be descriptive of why the validation fails. 
If capital letters are allowed, then the validation should be fixed

## Possible Solution
-

## Environment

<pre><code>
Ergonode version: 1.0.0-beta.8
 
Detailed information:
PHP version - 7.4

Others:
-
</pre></code>

**Comment by piotrkreft** [comment]
hi @kardi31 you are correct. The problem here is the validation. Input should allow capital letters but only lower-cased code should be persisted.
Would you mind provided a fix?

**Comment by piotrkreft** [comment]
Closing as no longer relevant on current master branch
