### ISSUE TITLE
Local attributes' values not being removed on product template

### ISSUE THREAD

**Issue by kardi31** [ergonode/backend#1738]
## Bug type 
Architecture

## Reproduce steps:
1. I add new SELECT attribute with scope local. 
2. I assign new attribute to a template.
3. I select attribute value on product X template & save the product.
4. I clear attribute value on product X & save the product
5. I remove attribute from a template
6. I attempt to remove attribute

## Expected outcome : 
attribute is removed

## Actual outcome : 
Error message is displayed that the attribute is connected to product X

## Debugging results : 
When I unset attribute value on product template, the value is saved as null. For example, for attribute with scope local, the value looks like `en_GB = null, pl_PL = null`. When attempting to remove attribute, the relationship between product & attribute still exists even though all the values are `null`. Product attribute updater do not check in any place whether attribute has not empty values. 

## Environment

<pre><code>
Ergonode version: 1.1.4

 
</code></pre>

**Comment by rprzedzik** [comment]
In the case of local attributes, entering an 'empty' value for a language does not delete it, but overwrites the with empty value with its ancestor in the language tree.

If it is necessary to delete a value for a language, it should not be overwritten. This can be done from the tab edit product values using the dedicated functionality

![obraz](https://user-images.githubusercontent.com/46092482/142873672-759a5f43-94c3-4024-8d19-c48d96d01cef.png)

**Comment by kardi31** [comment]
@rprzedzik 
Ok, but what if a product has all values for certain attribute as empty? Should such value not be deleted completely?
 Also from user experience perspective, I'd expect "clear all" button to remove value for this attribute, not just empty it. 
![clearall](https://user-images.githubusercontent.com/9740794/143231078-4c8717ca-cc3b-4133-a7a1-86814b9b3284.PNG)
