### ISSUE TITLE
Where is the documentation on REST API

### ISSUE THREAD

**Issue by onepack** [ergonode/backend#1881]
* Community Chat: Links: [discord](https://discord.gg/NntXFa4)
* Twitter: If it's just a quick question you can ping our [Twitter](https://twitter.com/ergonode)

According to the documentation there is a REST API.
https://www.ergonode.com/features/api-first

However, I can't find anything in https://docs.ergonode.com/

Am I missing something?

**Comment by piotrkreft** [comment]
@onepack REST API documentation is to be found on `/api/doc` path of your instance. I do not however recommend this API for external integration as this APIs main purpose is internal data presentation and UI - the API is not covered with a strong backward compatibility promise and thus is subject to change.
If need help in the regard please get in touch with support via [issues.ergonode.com](https://ergonodesupport.atlassian.net/servicedesk/customer/user/login?destination=portals) or via Community Ergonode Slack.
This is an obsolete repository and maintained anymore.
Best of luck!
