### ISSUE TITLE
Documentation for test username/pass incorrect

### ISSUE THREAD

**Issue by peterjaap** [ergonode/backend#716]
## Bug type
Documentation

## Current behavior
Documentation says on the [Phing commands page](https://docs.ergonode.com/#/backend/installation?id=phing-commands); 

![image](https://user-images.githubusercontent.com/431360/91721276-c9b72200-eb98-11ea-8a97-b0f35b881373.png)

## Expected behavior
That is incorrect, the password is not `123` but `abcd1234` as can be read in the [README.md](https://github.com/ergonode/backend/blob/develop/README.md) file.

## Possible Solution
Fix docs

## Environment

<pre><code>
Ergonode version: X.Y.Z

 
Detailed information:
- PHP version: 

Others:

</code></pre>

**Comment by derpdead** [comment]
@peterjaap Thank you for your report, we are working at Docs.

**Comment by wiewiurdp** [comment]
Documentation was updated
