### ISSUE TITLE
api/v1/en/dictionary/channels gives 404

### ISSUE THREAD

**Issue by peterjaap** [ergonode/backend#717]
## Bug type
Code?

## Current behavior
I installed Ergonode backend (with dev fixtures) and frontend. When I open up http://localhost:3000 and log in, I'm shown a 404;

![image](https://user-images.githubusercontent.com/431360/91723668-6a5b1100-eb9c-11ea-8f74-6082bb05a761.png)

The channels endpoint is the only one that gives a 404, all the other ones give 200;

![image](https://user-images.githubusercontent.com/431360/91723788-9b3b4600-eb9c-11ea-9dcd-95e161f17db3.png)

When I refresh, I see raw HTML:

![image](https://user-images.githubusercontent.com/431360/91723641-5ca58b80-eb9c-11ea-9142-bcc5633d7f09.png)

When I look in the console where I started `npm run dev`, I see a 404 notice;

```
{
...
  },
  data: {
    code: '404',
    message: 'No route found for "GET /api/v1/en/dictionary/channels"',
    exception: {
      current: [Object],
      previous: [Object]
    }
  }
}
```

## Expected behavior
The dashboard should be shown.

## Possible Solution
No idea.

## Environment

<pre><code>
Ergonode version: latest

 
Detailed information:
- PHP version: 7.4

Others:

</code></pre>

**Comment by derpdead** [comment]
@peterjaap Could you give us more info? Which branches for BE and FE? master or develop?

**Comment by peterjaap** [comment]
@derpdead 

BE: master
FE: develop

Both latest commit checked out.

**Comment by derpdead** [comment]
@peterjaap Channels are not existing at master branch of BE (release 0.9). You must to use either develops nor masters. Otherwise you might get not synchronised features.

**Comment by peterjaap** [comment]
@derpdead thanks, that was it! :)
